### ISSUE TITLE
[ENHANCEMENT] respect privacy with error/data reports

### ISSUE THREAD

**Issue by mueslimak3r** [ABJC/ABJC-tvOS#48]
The privacy policy when the app is launched says info like server url will be collected.

Please implement a way to scrub urls and API keys from the logs before they are sent to the developer.

Or add an opt-out button. If your app is used in the EU or california you also need to comply with GDPR & CCPA, and an opt-out button could make this simple

This should be possible with a simple regex

**Comment by noahkamara** [comment]
Oops. That’s that old notice. Error text is not part of reports, only error codes (since Jellyfin doesn’t send proper errors anyway). The notice was from early development of analytics. It’ll be changed in the next build.

errors look like this:

ˋˋˋ

device: "Apple TV 4K 2nd Gen“

os: 
  name: "tvOS"
  version: "15.2"
version:
  build: 29
  major: 1
  minor: 0
  patch: 0
  version: "[BETA] 1.0.0 (29)"

data:
  code: 400
  error-code: 4
  error-domain: "JellyfinAPI.DecodableRequestBuilderError"
  error-label: "400"

event: "network-error"
id: "XXXXXXX-xxxx-XXXX-xxxx-xXxxxxxxxx"

metadata:
  error-location:
    file: "/UI/Views/AuthenticationView/AuthenticationViewDelegate.swift"
    function: "authenticate(username:password:)"
    line: 182
    state: "userManual"
    view: auth
  timestamp: 1638070016

ˋˋˋ

The analytics will be mandatory in TestFlight but optional in release, which is compliant with GDPR & CCPA because no personal data is collected. 

Logs aren’t sent because I haven’t implemented a way to scrub urls and api keys yet.
When I implement a way to send logs (they’re never gonna be sent automatically) I will also implement scrubbing for privacy sensitive data
